services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - API_URL=${API_URL}
    volumes:
      - ./api:/app

  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "80:80"
      - "5173:5173"
    env_file:
      - .env
    environment:
      - VITE_API_URL=${VITE_API_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api 