apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ghcr-secret
  namespace: "{{ .Release.Namespace }}"
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: pumpkin-fz-wl
        envSlug: production
        secretsPath: /GHCR_EI
      credentialsRef:
        secretName: veronica-machine-credentials
        secretNamespace: infisical
  managedSecretReference:
    secretName: ghcr-secret
    secretNamespace: "{{ .Release.Namespace }}"
    creationPolicy: Owner
    secretType: kubernetes.io/dockerconfigjson
    dataFrom:
      - key: .dockerconfigjson
        secretKey: .dockerconfigjson
