apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.api.name }}
  labels:
    app: {{ .Values.api.name }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    app: {{ .Values.frontend.name }} 