apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs
spec:
  hosts:
  - {{ .Values.global.domain | quote }}
  gateways:
  - {{ .Release.Name }}-gateway
  http:
  - match:
    - uri:
        prefix: "/.well-known/acme-challenge/"
    route:
    - destination:
        host: cm-acme-http-solver.istio-system.svc.cluster.local
        port:
          number: 8089
  - match:
    - uri:
        prefix: "/api/"
    rewrite:
      uri: "/"
    headers:
      request:
        set:
          x-debug-forwarded-for: "%REQ(X-FORWARDED-FOR)%"
          x-debug-source-ip: "%DOWNSTREAM_REMOTE_ADDRESS%"
          x-debug-real-ip: "%REQ(X-REAL-IP)%"
          x-debug-remote-addr: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
          x-debug-original-dst: "%REQUESTED_SERVER_NAME%"
          x-debug-protocol: "%PROTOCOL%"
    route:
    - destination:
        host: {{ .Values.api.name }}
        port:
          number: {{ .Values.api.service.port }}
  - match:
    - uri:
        prefix: "/"
    headers:
      request:
        set:
          x-debug-forwarded-for: "%REQ(X-FORWARDED-FOR)%"
          x-debug-source-ip: "%DOWNSTREAM_REMOTE_ADDRESS%"
          x-debug-real-ip: "%REQ(X-REAL-IP)%"
          x-debug-remote-addr: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
          x-debug-original-dst: "%REQUESTED_SERVER_NAME%"
          x-debug-protocol: "%PROTOCOL%"
    route:
    - destination:
        host: {{ .Values.frontend.name }}
        port:
          number: {{ .Values.frontend.service.port }}
