apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs
spec:
  hosts:
  - {{ .Values.global.domain | quote }}
  gateways:
  - {{ .Release.Name }}-gateway
  http:
  - match:
    - uri:
        prefix: "/api/"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: {{ .Values.api.name }}
        port:
          number: {{ .Values.api.service.port }}
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: {{ .Values.frontend.name }}
        port:
          number: {{ .Values.frontend.service.port }}
