name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create package if not exists
        run: |
          gh api --method PUT /user/packages/container/weekly-ingestor-backend/visibility \
            -f visibility="public" || true
          gh api --method PUT /user/packages/container/weekly-ingestor-frontend/visibility \
            -f visibility="public" || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/weekly-ingestor/weekly-ingestor-backend
            ghcr.io/${{ github.repository_owner }}/weekly-ingestor/weekly-ingestor-frontend
          tags: |
            type=sha,format=short
            type=ref,event=branch
            type=semver,pattern={{version}}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/weekly-ingestor/weekly-ingestor-backend:latest
            ghcr.io/${{ github.repository_owner }}/weekly-ingestor/weekly-ingestor-backend:sha-${{ github.sha }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          target: production
          push: true
          build-args: |
            VITE_API_URL=https://weekly-ingestor.crichard.fr/api
          tags: |
            ghcr.io/${{ github.repository_owner }}/weekly-ingestor/weekly-ingestor-frontend:latest
            ghcr.io/${{ github.repository_owner }}/weekly-ingestor/weekly-ingestor-frontend:sha-${{ github.sha }}
